### PR TITLE
Wireguard PersistentKeepAlive param

### LINKED ISSUE #5167: Allow enabling PersistentKeepalive for wireguard enabled setup
I'm observing an issue with connectivity (on internal wireguard IPs ``192.168.x.x``) from nodes on public network to node, which is inside private cloud / behind cloud provider firewall. The issue disappears immediately after I ping those nodes from the affected node inside private cloud (pings in the other direction get unstuck). The connectivity works as long as there is some traffic sent in that direction from time to time.

From what I managed to find about wireguard, this seems to be the issue of some firewall / networking gear blocking up inactive routes and could be solved by using ``PersistentKeepalive`` feature.

## Expected Behavior
Connectivity between nodes and pods persists even after periods of no traffic between given pair of nodes and direction.

## Current Behavior
After a few hours of no traffic from ``node1`` to ``node2`` the packets from ``node2`` to ``node1`` stop being routable. The problem is fixed immediately after any packet is sent from ``node1`` to ``node2``.

Note that the first ping from ``node1`` to ``node2`` has higher latency:
```
ING 192.168.96.193 (192.168.96.193) 56(84) bytes of data.
64 bytes from 192.168.96.193: icmp_seq=1 ttl=64 time=41.1 ms
64 bytes from 192.168.96.193: icmp_seq=2 ttl=64 time=19.8 ms
64 bytes from 192.168.96.193: icmp_seq=3 ttl=64 time=20.0 ms
```

as I suppose it is triggering the firewall to evaluate and re-open the route.

## Possible Solution
I suspect wireguard's _persistent keepalives_ might solve the issue. According to documentation this feature may be specified by adding the ``PersistentKeepalive =`` field to a peer in the configuration file, or setting ``persistent-keepalive`` at the command line.
I would like my calico setup to have this setting, I suppose it needs a new config flag to be added.

## Steps to Reproduce (for bugs)
1. create node1 on public vps
2. create node2 on private cloud vps (in my case oracle cloud)
3. connect them into calico node-to-node mesh, but without any workload that would send traffic from node2 to node1
4. after few hours observe that you can't send traffic from pods on node1 to pods in node2 (or even ping the node wireguard internal ip)

## Context
Right now pinging internal ips of other nodes fixes the issue and keeping e.g. webpage open that uses node2->node1 route keeps it going, after I close the page the problem will appear soon. 

## Your Environment
* Calico version ``calico/node:v3.21.1``
* Orchestrator version (e.g. kubernetes, mesos, rkt): ``k3s`` 
* Operating System and version: ``5.13.0-22-generic`` ``Ubuntu 21.10`` ``kubelet version v1.22.2+k3s2``

### PR DESCRIPTION
**Pull request by makhov**
Signed-off-by: makhov <makhov.alex@gmail.com>

## Description

By default, WireGuard peers remain silent while they do not need to communicate, so peers located behind a NAT and/or firewall may be unreachable from other peers until they reach out to other peers themselves (or the connection may time out). Adding PersistentKeepalive to the [Peer] settings of a peer located behind a NAT and/or firewall can ensure that the connection remains open. 

See: https://www.wireguard.com/quickstart/#nat-and-firewall-traversal-persistence

## Related issues/PRs

fixes #5167

## Todos

- [ ] Tests
- [x] Documentation
- [x] Release note

## Release Note

```release-note
Wireguard PersistentKeepAlive enabled by default and wireguardKeepAlive parameter added to control PersistentKeepAlive option. 
```

### CODE REVIEW

**Comment by makhov** [comment]
@caseydavenport 
Hi! What do you think about the feature? It would be good to have a fix for #5167.

**Comment by caseydavenport** [comment]
@makhov sorry, I missed this one! Will take a look now.

File: felix/config/config_params.go [hunk 1]
```diff
@@ -160,12 +160,13 @@ type Config struct {
...
-	WireguardInterfaceName         string `config:"iface-param;wireguard.cali;non-zero"`
-	WireguardMTU                   int    `config:"int;0"`
-	WireguardHostEncryptionEnabled bool   `config:"bool;false"`
+	WireguardEnabled               bool          `config:"bool;false"`
+	WireguardListeningPort         int           `config:"int;51820"`
+	WireguardRoutingRulePriority   int           `config:"int;99"`
+	WireguardInterfaceName         string        `config:"iface-param;wireguard.cali;non-zero"`
+	WireguardMTU                   int           `config:"int;0"`
+	WireguardHostEncryptionEnabled bool          `config:"bool;false"`
+	WireguardPersistentKeepAlive   time.Duration `config:"seconds;25"`
```
Comment (caseydavenport) [inline felix/config/config_params.go:169]: We may want this to be a pointer so that we can default to the current behavior - is there any chance users will want to opt-out of this behavior?

Comment (caseydavenport) [reply felix/config/config_params.go:169]: From a quick search, I think we will need to make this disabled by default and an opt-in feature - I suspect most wireguard users will want this disabled unless using a NAT / etc.

**Review by electricjesus — APPROVED** [review]
LGTM

File: felix/config/config_params.go (hunk 1 above)
Comment (mikestephen) [reply felix/config/config_params.go:169]: If a value of 0 disables the keepalive, should 0 be the default?

Comment (caseydavenport) [reply felix/config/config_params.go:169]: Yeah, we should update this to 0 and we should change the FelixConfiguration API documentation to indicate that the field is default off.

**Comment by caseydavenport** [comment]
@makhov just one comment - we should make this default OFF instead of opt-out.

File: felix/config/config_params.go (hunk 1 above)
Comment (makhov) [reply felix/config/config_params.go]: Changed default value to 0

File: calico/_includes/charts/calico/crds/kdd/crd.projectcalico.org_felixconfigurations.yaml [hunk 2]
```diff
@@ -549,6 +549,10 @@ spec:
                 description: 'WireguardRoutingRulePriority controls the priority value
                   to use for the Wireguard routing rule. [Default: 99]'
                 type: integer
+              wireguardPersistentKeepAlive:
+                description: 'WireguardPersistentKeepAlive controls Wireguard 
+                  PersistentKeepalive option. Set 0 to disable. [Default: 25s]'
```
Comment (caseydavenport) [inline calico/_includes/charts/calico/crds/kdd/crd.projectcalico.org_felixconfigurations.yaml:554]: This still says default: 25s

**Review by caseydavenport — APPROVED** [review]

File: calico/_includes/charts/calico/crds/kdd/crd.projectcalico.org_felixconfigurations.yaml (hunk 2 above)
Comment (makhov) [reply calico/_includes/charts/calico/crds/kdd/crd.projectcalico.org_felixconfigurations.yaml]: Sorry, missed this one. Fixed

**Comment by caseydavenport** [comment]
Just some failing tests remain before merging this. These are the ones that I can see right now: 

A few tests are picking up a new config field that they don't expect: 

```
Summarizing 5 Failures:03:23
[Fail] Test the generic configuration update processor and the concrete implementations [It] should handle conversion of node-specific delete with no additional configs 03:23
/go/src/github.com/projectcalico/calico/libcalico-go/lib/backend/syncersv1/updateprocessors/configurationprocessor_test.go:36903:23
[Fail] Test the generic configuration update processor and the concrete implementations [It] should handle conversion of global delete with no additional configs 03:23
/go/src/github.com/projectcalico/calico/libcalico-go/lib/backend/syncersv1/updateprocessors/configurationprocessor_test.go:36903:23
[Fail] Test the generic configuration update processor and the concrete implementations [It] should handle conversion of node-specific zero value KVPairs with no additional configs 03:23
/go/src/github.com/projectcalico/calico/libcalico-go/lib/backend/syncersv1/updateprocessors/configurationprocessor_test.go:36903:23
[Fail] Test the generic configuration update processor and the concrete implementations [It] should handle conversion of global zero value KVPairs with no additional configs 03:23
/go/src/github.com/projectcalico/calico/libcalico-go/lib/backend/syncersv1/updateprocessors/configurationprocessor_test.go:36903:23
[Fail] Test the generic configuration update processor and the concrete implementations [It] should handle different field types being assigned 03:23
/go/src/github.com/projectcalico/calico/libcalico-go/lib/backend/syncersv1/updateprocessors/configurationprocessor_test.go:369
```

This should be fixed by running `make fix` across the code. 

```
./calicoctl/commands/crds/crds.go08:45
../lib.Makefile:540: recipe for target 'check-fmt' failed
```

**Comment by makhov** [comment]
@caseydavenport fixed the test

**Comment by caseydavenport** [comment]
Remaining test failure is a known flake, so this LGTM!

**Comment by caseydavenport** [comment]
This just missed the boat for v3.22, which is in code-freeze right now, so moved to v3.23.
