### PR TITLE
Fix UID for v3 resources in KDD mode

### LINKED ISSUE #5715: Calico Apiserver not delete Resource with OwnerReference
I have an operator which create a networkpolicies.projectcalico.org/v3 with a OwnerRefernce and when I delete my Custom Resource, the networkpolicies.projectcalico.org/v3 is not deleted.

## Expected Behavior
I expect that the deletion of my Custom Resources delete at the same time the networkpolicies.projectcalico.org/v3 (with the OwnerReference)

## Current Behavior
When I delete my Custom Resources, the networkpolicies.projectcalico.org/v3 is not deleted.

## Steps to Reproduce (for bugs)
1. Create a resource 
2. Create networkpolicies.projectcalico.org/v3 with OwnerReference of last created resource
3. Delete with kubectl the step 1' resource

## Context
The Calico Api Server is deployed inside the cluster

My Custom Resource :
```
apiVersion: mycrd.fr/v1alpha1
kind: FluxNP
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"mycrd.fr/v1alpha1","kind":"FluxNP","metadata":{"annotations":{},"name":"ext","namespace":"test"},"spec":{"allow":true,"interval":3600}}
  creationTimestamp: "2022-03-07T16:03:18Z"
  generation: 1
  name: ext
  namespace: test
  resourceVersion: "16336"
  uid: 0e5e3214-5bda-429e-8d53-2f1b77363286
spec:
  allow: true
  interval: 3600
status:
  lastUpdated: "2022-03-07T16:03:18Z"
  revision: 1
```

The networkpolicies.projectcalico.org/v3 : 
```
apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  creationTimestamp: "2022-03-07T16:03:18Z"
  name: ext
  namespace: test
  ownerReferences:
  - apiVersion: mycrd.fr/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: FluxNP
    name: ext
    uid: 0e5e3214-5bda-429e-8d53-2f1b77363286
  resourceVersion: "16335"
  uid: f14af896-94a3-453c-a9b1-4a29aaa9e20f
spec:
  egress:
  - action: Allow
    destination: {}
    source: {}
  types:
  - Egress
```

## Your Environment
* Calico version : 3.22.1
* Orchestrator version (e.g. kubernetes, mesos, rkt): rk2 1.21.5
* Operating System and version: Redhat 8.2

### PR DESCRIPTION
**Pull request by fasaxc**
## Description

Picking up the fix for #5715.  Looks like we adopted this fix in Calico Enterprise already so let's be consistent.

## Related issues/PRs

fixes #5715

## Todos

- [ ] Tests
- [ ] Documentation
- [ ] Release note

## Release Note

```release-note
Fix that Calico API server would reuse UUIDs from the underlying CRD objects that underpin the datamodel (thus confusing Kubernetes ownership tracking and ArgoCD).  This will result in the apparent UUIDs of calico "v3" resources changing over upgrade.  This was unavoidable in order to split them from the underlying CRD UUIDs.
```

## Reminder for the reviewer

Make sure that this PR has the correct labels and milestone set.

Every PR needs one `docs-*` label.

- `docs-pr-required`: This change requires a change to the documentation that has not been completed yet.
- `docs-completed`: This change has all necessary documentation completed.
- `docs-not-required`: This change has no user-facing impact and requires no docs.

Every PR needs one `release-note-*` label.

- `release-note-required`: This PR has user-facing changes. Most PRs should have this label.
- `release-note-not-required`: This PR has no user-facing changes.

Other optional labels:

- `cherry-pick-candidate`: This PR should be cherry-picked to an earlier release. For bug fixes only.
- `needs-operator-pr`: This PR is related to install and requires a corresponding change to the operator.

### CODE REVIEW

File: libcalico-go/lib/backend/k8s/resources/customresource.go [hunk 1]
```diff
@@ -1,4 +1,4 @@
-// Copyright (c) 2017-2019,2021 Tigera, Inc. All rights reserved.
+// Copyright (c) 2017-2019,2021-2022 Tigera, Inc. All rights reserved.
```
Comment (caseydavenport) [inline libcalico-go/lib/backend/k8s/resources/customresource.go:1]: It's 2023 now :grin:

**Review by caseydavenport — APPROVED** [review]

**Comment by marvin-tigera** [comment]
OK, I will merge the pull request when it's ready, leave the commits as is when I merge it, and leave the branch after I've merged it.
