### PR TITLE
Fix panic when BGP is off

### LINKED ISSUE #1643: calico-node(v3.0.1) panic when in canal setup using etcd datastore
When I was testing out Canal manifests for #1642 (actually using the v3.0.1 release, not master) I hit the following panic when installing fresh or doing an upgrade and using an etcd datastore.

```
core@k8s-master ~ $ kubectl logs -n kube-system canal-node-z9qwj -c calico-node
2018-01-26 21:30:41.359 [INFO][7] startup.go 187: Early log level set to info
2018-01-26 21:30:41.359 [INFO][7] startup.go 198: NODENAME environment not specified - check HOSTNAME
2018-01-26 21:30:41.360 [INFO][7] startup.go 100: Skipping datastore connection test
2018-01-26 21:30:41.366 [INFO][7] startup.go 153: Using node name: k8s-node-01
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x112af56]

goroutine 1 [running]:
main.removeHostTunnelAddr(0x1c8ef60, 0xc42000e1e8, 0x1c95f20, 0xc42011cd80, 0xc42000a149, 0xb)
        /go/src/github.com/projectcalico/calico/calico_node/allocateipip/allocate_ipip_addr.go:112 +0xf6
main.main()
        /go/src/github.com/projectcalico/calico/calico_node/allocateipip/allocate_ipip_addr.go:56 +0x1da
Calico node failed to start
```

## Expected Behavior
calico-node works and applies policy

## Current Behavior
calico-node panics

## Possible Solution
Fix it

## Steps to Reproduce (for bugs)
1. Setup according to the docs in #1642
2. Check the calico-node logs after applying the Canal manifest

## Context
Found while trying to test out updated Canal manifest.

## Your Environment

* Calico version
* Orchestrator version (e.g. kubernetes, mesos, rkt):
* Operating System and version:
* Link to your project (optional):

### PR DESCRIPTION
**Pull request by tmjd**
## Description

Fixes #1643

## Todos

- [X] Tests
  - [X] Test this out with Canal setup

## Release Note

```release-note
None required
```

### CODE REVIEW

**Comment by tmjd** [comment]
I built calico node and tested it with the same manifest that originally produced this panic in #1643.

File: calico_node/allocateipip/allocate_ipip_addr.go [hunk 1]
```diff
@@ -74,7 +74,7 @@ func ensureHostTunnelAddress(ctx context.Context, c client.Interface, nodename s
 		log.WithError(err).Fatalf("Unable to retrieve IPIP tunnel address. Error getting node '%s'", nodename)
 	}
 
-	if node.Spec.BGP.IPv4IPIPTunnelAddr == "" {
+	if node.Spec.BGP == nil || node.Spec.BGP.IPv4IPIPTunnelAddr == "" {
```
Comment (caseydavenport) [inline calico_node/allocateipip/allocate_ipip_addr.go]: Hm, I wonder if we ever want to assign an IPIP tunnel address if the BGP spec is `nil` - seems like in this case we really want to remove any tunnel address (since BGP isn't being used, and thus IPIP won't be either).

The cases where BGP is nil:
- Using canal or something other than Calico BGP for routing.
- When IPIP is disabled and a BGP IP address conflict is detected, BGP spec will be temporarily nil

WDYT?

Comment (tmjd) [reply calico_node/allocateipip/allocate_ipip_addr.go]: I'm not sure I follow what you are suggesting.

> if the BGP spec is nil - seems like in this case we really want to remove any tunnel address

If BGP spec is nil then we don't have the tunnel address to remove.

> When IPIP is disabled and a BGP IP address conflict is detected, BGP spec may be temporarily nil

I don't think this code will be executed because ensureHostTunnelAddress is only called when there is an IPIP enabled pool.

Comment (caseydavenport) [reply calico_node/allocateipip/allocate_ipip_addr.go]: > I don't think this code will be executed because ensureHostTunnelAddress is only called when there is an IPIP enabled pool.

Er, yeah I meant when `node.Spec.BGP.IPv4IPIPTunnelAddr == ""`, sometimes the BGP spec will be set to nil. I think we can ignore that scenario though because we won't reach this code.

> If BGP spec is nil then we don't have the tunnel address to remove.

Well, technically it might still be allocated in IPAM and we'd want to remove it, but I don't think we've got the infra in place to do that since right now we require having the IP in-hand in order to free it.

I guess my point was that if the BGP spec is `nil`, then why would we assign a tunnel address? I don't _think_ there are any cases where the BGP spec is nil and we'd want to assign a tunnel address.

That said, I don't think it really hurts, so I'm happy to leave it as it's written right now and see if we get feedback.

Comment (tmjd) [reply calico_node/allocateipip/allocate_ipip_addr.go]: Like we talked about I'll add a new `if` branch for if BGP spec is nil to log and then return back.
