### PR TITLE
Convert NODENAME/HOSTNAME envs to lowercase

### LINKED ISSUE #1572: calico/node refuses to start if hostname is not lower case
User **madianjun** on calico users found that calico/node wouldn't start on their system, the logs show that the problem is an "invalid" hostname:

```
2018-01-03 13:24:49.147 [INFO][9] startup.go 187: Early log level set to info
2018-01-03 13:24:49.147 [INFO][9] startup.go 198: NODENAME environment not specified - check HOSTNAME
2018-01-03 13:24:49.149 [INFO][9] startup.go 100: Skipping datastore connection test
2018-01-03 13:24:49.150 [INFO][9] startup.go 271: Building new node resource Name="BJYFB3-Druid-18292.hadoop.jd.local"
2018-01-03 13:24:49.150 [INFO][9] startup.go 286: Initialize BGP data
2018-01-03 13:24:49.151 [INFO][9] startup.go 497: Using autodetected IPv4 address 172.19.182.92/24 on matching interface bond0
2018-01-03 13:24:49.151 [INFO][9] startup.go 351: Node IPv4 changed, will check for conflicts
2018-01-03 13:24:49.152 [INFO][9] startup.go 546: No AS number configured on node resource, using global value
2018-01-03 13:24:49.153 [ERROR][9] startup.go 135: Unable to set node resource configuration error=error with field Metadata.Name = 'BJYFB3-Druid-18292.hadoop.jd.local' (name must consist of lower case alphanumeric characters, '-' or '.' (regex: [a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*))
2018-01-03 13:24:49.153 [WARNING][9] startup.go 943: Terminating
Calico node failed to start
```
## Expected Behavior

`calico/node` should start up

## Current Behavior

`calico/node` fails to start

## Possible Solution

Cast the name to lower case?

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Calico version
* Orchestrator version (e.g. kubernetes, mesos, rkt):
* Operating System and version:
* Link to your project (optional):

### PR DESCRIPTION
**Pull request by robbrockbank**
## Description

Convert the NODENAME and HOSTNAME environments to lowercase.

I'm not sure about this fix.
-  Should we only convert the HOSTNAME (since it's the fact that the HOSTNAME may be populated by the OS that we need to address)
-  Should we just retire the use of the HOSTNAME environment (which I believe was always the plan), but it feels like it's too late to do that now.
-  Do we need to make similar changes to the CNI plugin?

Fixes #1572 

## Todos

- [ ] Tests
- [ ] Documentation
- [ ] Release note

## Release Note

```release-note
None required
```

### CODE REVIEW

File: calico_node/startup/startup.go [hunk 1]
```diff
@@ -190,26 +190,33 @@ func configureLogging() {
...
+		log.Warn("Using auto-detecting node name. It is recommended that an explicit value is supplied using " +
+			"the NODENAME environment variable.")
 	}
-	return nodeName
+
+	// Ensure the node name is lowercase and has no leading/trailing whitespace.  We'll log
+	// if the name is actually modified by the case conversion.
+	finalNodeName := strings.ToLower(nodeName)
+	if finalNodeName != nodeName {
+		log.Warn("Converted node name to lowercase: %s -> %s")
```
Comment (bcreane) [inline calico_node/startup/startup.go]: oops - you want to pass in finaleNodeName and nodeName

File: calico_node/startup/startup.go [hunk 2]
```diff
@@ -190,26 +190,33 @@ func configureLogging() {
...
+		terminate()
+	} else {
+		log.Warn("Using auto-detected node name. It is recommended that an explicit value is supplied using " +
+			"the NODENAME environment variable.")
 	}
-	return nodeName
+
+	// Ensure the node name is lowercase and has no leading/trailing whitespace.  We'll log
+	// if the name is actually modified by the case conversion.
+	finalNodeName := strings.ToLower(nodeName)
```
Comment (caseydavenport) [inline calico_node/startup/startup.go]: I'm conflicted on this one... 

On the one hand I'm a bit loathe to change something that was provided by the user here... if they've given us a hostname with capital letters then who are we to convert that to lowercase?

On the other hand, hostnames are case-insensitive, so it should be OK. However... this isn't a "hostname" - it's a Calico nodename, which is something subtly different from a hostname even though it has the same validation requirements. 

hmmm

Comment (caseydavenport) [reply calico_node/startup/startup.go]: I guess it's Ok, and we'll see if anyone complains about it.

File: calico_node/startup/startup.go [hunk 3]
```diff
@@ -190,26 +190,33 @@ func configureLogging() {
...
-		}
-		log.Warn("Auto-detecting node name. It is recommended that an explicit value is supplied using the NODENAME environment variable.")
+	var nodeName string
+	var err error
+
+	// Determine the name of this node.  Precedence is NODENAME, HOSTNAME, os.Hostname.
+	// We use the names.Hostname which lowercases and trims the name.
+	if nodeName = strings.TrimSpace(os.Getenv("NODENAME")); nodeName != "" {
+		log.Infof("Using NODENAME environment for node name")
+	} else if nodeName = strings.TrimSpace(os.Getenv("HOSTNAME")); nodeName != "" {
```
Comment (caseydavenport) [inline calico_node/startup/startup.go]: Aw man, I thought we deprecated and removed HOSTNAME is v3.0

Comment (robbrockbank) [reply calico_node/startup/startup.go]: Indeed!  If we had removed HOSTNAME then I have no hestitation in saying "NODENAME" should be correct.

However, the real issue is the HOSTNAME parm because that may be set by the OS.

Perhaps we should just adjust the HOSTNAME and os.Hostname, but leave NODENAME - under the assumption that if it's set it'll be correct.

**Comment by robbrockbank** [comment]
@caseydavenport @bcreane @fasaxc 

Expecting either a thumbs up, or a "only lowercase the HOSTNAME and not the NODENAME"...  WDYT?

**Comment by fasaxc** [comment]
Definitely lower case `os.Hostname()`, and either remove, or lower case, the `HOSTNAME` env var. 

Not too worried about NODENAME but maybe we should document that it needs to be lower case in its description?

File: calico_node/startup/startup.go (hunk 2 above)
Comment (caseydavenport) [reply calico_node/startup/startup.go]: OK. I think we agreed that:

- NODENAME should not be altered
- HOSTNAME should be automatically lowercased 
- names.Hostname() already handles casing.
