### PR TITLE
Fix skb_is_gso for CO-RE capable kernels.

### LINKED ISSUE #5575: Performance issue with eBPF enabled in a multi-node setup (working without eBPF)
When  traffic comes into the calico network (from the edge), so something that crosses a LoadBalancer into the network, the performance is maxed out at 5MB/s (iperf3). 

There is no ingress in between, it is plain `LoadBalancer` and the iperf3.

## Expected Behavior
It should at least perform as well as non-eBPF, which is about 4GB/s

## Current Behavior
Activating eBPF reduced the max. bandwidth to 5MB/s - this can be measured using iperf3 without and ingress (synthetic benchmark) or using an ingress and `docker push` workloads.

## Possible Solution
I have none

## Steps to Reproduce (for bugs)

It does only happen in multi-node environments. With a single node, the performance is normal with eBPF.
- enable eBPF (we use VXLAN (non CrossSubnet), non BGP) 
- use iperf e.g. using helm, e.g. via https://github.com/EugenMayer/helm-charts/tree/main/charts/iperf3
- measure the performance from any server in the same network / being close (to ensure no other bottlenecks)
- Switch from eBPF to Iptables - try the benchmark again. Should be a lot better

We used/tested this with quick-setups via RKE2 or k3s. E.g. using k3s use

```
curl -fL https://get.k3s.io | K3S_KUBECONFIG_MODE="640" INSTALL_K3S_EXEC="server --disable-kube-proxy --no-deploy=servicelb --disable=servicelb --disable-network-policy --flannel-backend=none --disable traefik --disable local-storage" sh -
```

Then install calico / tigera operator via the helm chart https://artifacthub.io/packages/helm/projectcalico/tigera-operator

## Context
- setup using terraform for 100% reproduceable / conform testing setups
- we deployed several setups from scratch without anything else the iperf and calico - no fuzz or extra layer
- we have an MTU of 1342 due to the provider network and our own OpenStack OVN. Calico seems to detect the MTU just fine

## Your Environment

* Calico version: tigera-operator v3.22.0 (helm chart)
* Orchestrator version (kubernetest):  `Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.6+k3s1", GitCommit:"3228d9cb9a4727d48f60de4f1ab472f7c50df904", GitTreeState:"clean", BuildDate:"2022-01-25T01:27:44Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}`
* Operating System and version: `VERSION="20.04.3 LTS (Focal Fossa)"`

### PR DESCRIPTION
**Pull request by sridhartigera**
## Description
skb_is_gso uses gso_size in the newer kernels (5.7 and above). Hence modifying the check to use gso_size for newer kernels and gso_segs for older kernels. BPF CO-RE is used to achieve this. We are compiling 2 different versions of the bpf binaries, one for CO-RE and other for non CO-RE. All CO-RE related calls should be placed under the compilation flag BPF_CORE_SUPPORTED. 

## Related issues/PRs

Fixes #5575 for CO-RE enabled kernels

## Todos

- [ ] Tests
- [ ] Documentation
- [ ] Release note

## Release Note

```release-note
None required
```

### CODE REVIEW

File: felix/bpf/tc/attach.go [hunk 1]
```diff
@@ -59,6 +59,7 @@ type AttachPoint struct {
 	PSNATEnd             uint16
 	IPv6Enabled          bool
 	MapSizes             map[string]uint32
+	BTFEnabled           bool
```
Comment (tomastigera) [inline felix/bpf/tc/attach.go:62]: Is this really attach point's feature? Does not seems so? What if we moved `SupportsBTF()` into `bpf/bpfutils` and call it in `init()` and set it as a global. We could just import `bpfutils` here and would not need to plumb through the whole configuration.

CTLB and other hooks we have could also use that information easily then.

File: felix/bpf/ut/precompilation_test.go [hunk 2]
```diff
@@ -41,66 +41,70 @@ func TestPrecompiledBinariesAreLoadable(t *testing.T) {
...
-					tc.EpTypeTunnel,
-					tc.EpTypeWireguard,
-				}
-				for _, epType := range epTypes {
-					epType := epType
-					logCxt = logCxt.WithField("epType", epType)
-					if epToHostDrop && epType != tc.EpTypeWorkload {
-						log.Debug("Skipping combination since epToHostDrop only affect workloads")
-						continue
+		for _, btfEnabled := range []bool{false, true} {
```
Comment (tomastigera) [inline felix/bpf/ut/precompilation_test.go:44]: would this work on a kernel that is not btf enabled? I think we want to run just the legacy non-co-re on such kernels and both on co-re capable kernels, right?

**Review by tomastigera — COMMENTED** [review]
LGTM, some suggestions

File: felix/bpf/ut/precompilation_test.go [hunk 3]
```diff
@@ -27,80 +27,92 @@ import (
...
-					tc.EpTypeWireguard,
-				}
-				for _, epType := range epTypes {
-					epType := epType
-					logCxt = logCxt.WithField("epType", epType)
-					if epToHostDrop && epType != tc.EpTypeWorkload {
-						log.Debug("Skipping combination since epToHostDrop only affect workloads")
-						continue
+		for _, btfEnabled := range checkBTFEnabled() {
+			bpfutils.BTFEnabled = btfEnabled
```
Comment (tomastigera) [inline felix/bpf/ut/precompilation_test.go:54]: Cool, LGTM, can we just do `defer bpfutils.BTFEnabled = bpfutils.SupportsBTF()` at the top of the test not to possibly pollute tests that follow?

File: felix/bpf/bpfutils/bpf_utils.go [hunk 4]
```diff
@@ -17,11 +17,27 @@ package bpfutils
...
+func SupportsBTF() bool {
+	_, err := os.Stat("/sys/kernel/btf/vmlinux")
+	if err != nil {
+		log.WithError(err).Debug("BTF not supported")
+		return false
+	}
+	return true
+}
+
+func init() {
```
Comment (tomastigera) [inline felix/bpf/bpfutils/bpf_utils.go:38]: can we make `init` the first function rather than have it lost somewhere in the middle?

**Review by tomastigera — APPROVED** [review]
LGTM thanks!
